hack/validate-blocked-edges: Python 2 compatability
Based on [1], ubi8.python.36 currently has:

* 'python' for 2.7.5
* 'python3' for 3.6.8

and the 'python' invocation was failing with [1]:

    File "/go/src/github.com/openshift/cincinnati-graph-data/hack/validate-blocked-edges.py", line 22
      raise ValueError('invalid blocked edge {}'.format(path)) from error
                                                                  ^
  SyntaxError: invalid syntax

That's because, while:

  raise ... from ...

works for Python 3 [2,3], the proposal to add it to Python 2 was
superseded [4,5].

From [6], we're using pip3 to install our dependencies, but when I
tried to invoke using python3, I got [7]:

  ModuleNotFoundError: No module named 'yaml'

So this commit pivots to syntax compatible with both Python 2 and
Python 3.

I've also added a check for the two properties required in all blocked
edges, even those which are not targted blockers.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22076/rehearse-22076-pull-ci-openshift-cincinnati-graph-data-master-validate-blocked-edges/1450657743043039232
[2]: https://www.python.org/dev/peps/pep-3109/
[3]: https://docs.python.org/3.6/reference/simple_stmts.html#raise
[4]: https://www.python.org/dev/peps/pep-0344/
[5]: https://docs.python.org/2.7/reference/simple_stmts.html#raise
[6]: https://github.com/openshift/release/blob/7e61829f682e1574513f78c3e94537836d824ab3/ci-operator/config/openshift/cincinnati-graph-data/openshift-cincinnati-graph-data-master.yaml#L21
[7]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22076/rehearse-22076-pull-ci-openshift-cincinnati-graph-data-master-validate-blocked-edges/1450662603784196096#1:build-log.txt%3A21