Downgrade actix-http to avoid `bytes` dep problem
Resolves this dependency issue I see after bumping o/cincinnati to dc2abd15d0:

```
$ cargo run --manifest-path graph-data.rs/Cargo.toml
    Updating git repository `https://github.com/openshift/cincinnati`
    Updating crates.io index
    Updating git repository `https://github.com/camallo/dkregistry-rs.git`
error: failed to select a version for `bytes`.
    ... required by package `cincinnati v0.1.0 (https://github.com/openshift/cincinnati?rev=dc2abd15d0336318829e6788000ac7418c29c2fc#dc2abd15)`
    ... which satisfies git dependency `cincinnati` of package `cincinnati-graph-data v0.1.0 (/home/pmuller/Projects/RH/github.com/openshift/cincinnati-graph-data/graph-data.rs)`
versions that meet the requirements `^1.5` are: 1.6.0, 1.5.0

all possible versions conflict with previously selected packages.

  previously selected package `bytes v1.1.0`
    ... which satisfies dependency `bytes = "^1"` (locked to 1.1.0) of package `actix-http v3.8.0`
    ... which satisfies dependency `actix-http = "=3.8.0"` (locked to 3.8.0) of package `cincinnati-graph-data v0.1.0 (/home/pmuller/Projects/RH/github.com/openshift/cincinnati-graph-data/graph-data.rs)`

failed to select a version for `bytes` which could resolve this conflict
```