hack/graph-util: Create missing major.minor dis in update_nodes
Avoid:

  $ hack/graph-util.py update-node quay.io/openshift-release-dev/ocp-release:4.2.0-rc.0
  Traceback (most recent call last):
    File "hack/graph-util.py", line 353, in <module>
      update_nodes(directory='.', pullspecs=args.pullspec)
    File "hack/graph-util.py", line 281, in update_nodes
      with open(os.path.join(directory, 'nodes', '{major}.{minor}'.format(**match.groupdict()), '{}.json'.format(meta['version'])), 'w+') as f:
  IOError: [Errno 2] No such file or directory: './nodes/4.2/4.2.0-rc.0.json'