hack/errata: Catch and retry on errors
For example:

  DEBUG:root:query page 1: https://datagrepper.engineering.redhat.com/raw?rows_per_page=100&delta=7200&category=errata&page=1&contains=RHOSE
  Traceback (most recent call last):
    File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
      h.request(req.get_method(), req.selector, req.data, headers)
    ...
    File "/usr/lib64/python3.4/socket.py", line 537, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno -2] Name or service not known

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "hack/errata.py", line 97, in <module>
    File "hack/errata.py", line 36, in run
    File "hack/errata.py", line 63, in poll
    File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
      return opener.open(url, data, timeout)
    ...
    File "/usr/lib64/python3.4/urllib/request.py", line 1185, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

The generic Exception catch is because we want this to keep running
regardless of what went wrong.