internal-channels/candidate: Remove 4.20.0-ec.1
4.20.0-ec.1 had a self-referencing update loop, as described in
a66ea0e885 (internal-channels/candidate: Tombstone 4.20.0-ec.1,
2025-06-02, #7379).  The release was subsequently deleted from Quay:

  $ for ARCH in multi aarch64 ppc64le s390x x86_64; do oc image info "quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-${ARCH}"; done
  error: unable to read image quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-multi: unknown: Tag 4.20.0-ec.1-multi was deleted or has expired. To pull, revive via time machine
  error: unable to read image quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-aarch64: unknown: Tag 4.20.0-ec.1-aarch64 was deleted or has expired. To pull, revive via time machine
  error: unable to read image quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-ppc64le: unknown: Tag 4.20.0-ec.1-ppc64le was deleted or has expired. To pull, revive via time machine
  error: unable to read image quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-s390x: unknown: Tag 4.20.0-ec.1-s390x was deleted or has expired. To pull, revive via time machine
  error: unable to read image quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-x86_64: unknown: Tag 4.20.0-ec.1-x86_64 was deleted or has expired. To pull, revive via time machine

Leading to graph-data CI failures like [1]:

  Error: Missing the following versions in scraped images: {Version { major: 4, minor: 20, patch: 0, pre: [AlphaNumeric("ec"), Numeric(1)], build: [] }}

due to graph-data.rs/src/check_releases.rs logic.  We don't usually
remove releases from channels, because we don't want to break updates
out to later versions for users running that release.  But in this
case, the candidate channel is internal, so users would never have
seen it in a public channel.  And the release image was deleted from
Quay, which would likely have already broken any clusters who may have
been running it on the first cluster-version operator Pod reschedule.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cincinnati-graph-data/7386/pull-ci-openshift-cincinnati-graph-data-master-e2e/1930972545192824832