Bump o/cincinnati to `dc2abd15` to match production
e2e tests recently
[fail](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cincinnati-graph-data/5457/pull-ci-openshift-cincinnati-graph-data-master-e2e/1805576375088713728):

```
Error: Missing the following versions in scraped images: {Version { major: 4, minor: 6, patch: 13, pre: [], build: [] }
```

Tracing the tests I saw the code only scrapes 20 releases from Quay which suggests some kind of pagination issues. Production cincinnati does not show any similar symptoms so there's a good chance that simply bumping the tests to run the same code helps.

Production cincinnati runs https://github.com/openshift/cincinnati/commit/dc2abd15d0336318829e6788000ac7418c29c2fc which is:

```
Author: openshift-ci[bot] <75433959+openshift-ci[bot]@users.noreply.github.com>
Date:   Fri Oct 13 13:13:52 2023 +0000

    Merge pull request #873 from openshift/dependabot/cargo/serde-1.0.189

    build(deps): bump serde from 1.0.183 to 1.0.189
```

But these tests run https://github.com/openshift/cincinnati/commit/a2974db3bf585296dafe23b1f4b734ce7217fa45 which is way older:

```
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Fri Dec 16 10:07:42 2022 -0500

    Merge pull request #743 from PratikMahajan/add-multi-e2e

    [e2e] add test for multi arch and update e2es for 134475077ed
```