hack/graph-util: Create missing edges/{major}.{minor}
Avoid:

  $ hack/graph-util.py extract-edges 4.2.0-rc.1
  Traceback (most recent call last):
    File "hack/graph-util.py", line 360, in <module>
      extract_edges_for_versions(directory='.', versions=args.version)
    File "hack/graph-util.py", line 319, in extract_edges_for_versions
      extract_edges(node=node, directory=os.path.join(directory, 'edges', '{major}.{minor}'.format(**match.groupdict()), version))
    File "hack/graph-util.py", line 303, in extract_edges
      with open(os.path.join(directory, '{}.json'.format(previous)), 'w+') as f:
  IOError: [Errno 2] No such file or directory: './edges/4.2/4.2.0-rc.1/4.1.18.json'